name: Delmania's Daily Musings
description: Developer, manager, father, human being
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
theme: jekyll-theme-tactile
